#Dependencies
markdown: kramdown
highlighter: rouge
## Permalinks
permalink:        pretty
## Setup
title:            Commelier
tagline:          'Android Developer'
description:      'Code + Sommelier<br>Android Developer<br>Seoul to anywhere'
url:              http://commelier.github.io
baseurl:          http://commelier.github.io

author:           'Commelier'
name:           'Commelier'
google_analytics_id: UA-140042027-1

plugins:
  - jekyll-paginate
  - jekyll-gist
paginate:         10

# Custom vars
version:          1.0.0

github:         commelier
repo:           https://github.com/commelier
twitter: sherrious_ryu
linked_in: bomee-ryu

collections:
  tags:
    output: true
    permalink: /tags/:path/

defaults:
  - scope:
      path: ''
      type: tags
    values:
      layout: tag
