# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Commelier
tagline:          'Android Developer'
description:      'I know my value<br>Android Developer<br>Seoul to anywhere'
url:              http://commelier.github.io
baseurl:          /

author:
  name:           'Commelier'
  url:            https://twitter.com/sherrious_ryu

paginate:         10

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/commelier
